### ISSUE TITLE
Bug: Imports broken in Deno / Feature request: Configure import extensions

### ISSUE THREAD

**Issue by NfNitLoop** [bufbuild/connect-es#595]
**Describe the bug**

For context, see [this comment](https://github.com/bufbuild/connect-es/issues/236#issuecomment-1220922357).
> Node.js has decided that [file extensions are mandatory](https://nodejs.org/api/esm.html#mandatory-file-extensions), and Microsoft has decided [not to rewrite import extensions](https://www.typescriptlang.org/docs/handbook/esm-node.html). That is why an import from "./foo.js" is the proper form in a TypeScript source file in a project with "type": "module", and we anticipate that it'll become the common form.

Unfortunately, that is not the form used in Deno, which is TypeScript-first. 

**To Reproduce**

```yaml
# buf.gen.yaml:
version: v1
managed:
  enabled: true
plugins:
  - plugin: buf.build/bufbuild/es
    opt: target=ts
    out: gen
  - plugin: buf.build/bufbuild/connect-es
    opt: target=ts
    out: gen
```

Create some `Example.proto`

`buf generate`

View `Example_connect.ts` and see that it imports 

```typescript
import { ... } from "./Example_pb.js";
```

But no such file exists.

**Environment (please complete the following information):**

`buf --versoin`: 1.17.0. 
connect-es: Whatever the remote plugin version is today, (April 27, 2023)

If your problem is specific to bundling, please also provide the following information: 

```
> deno --version
deno 1.32.2 (release, x86_64-pc-windows-msvc)
v8 11.2.214.9
typescript 5.0.3
```

**Comment by NfNitLoop** [comment]
Ah, from reading the other ticket, I thought configuring the import extension wasn't supported, but I saw in docs here that it is:

https://www.npmjs.com/package/@bufbuild/protoc-gen-connect-es

So updating my config to this fixes the problem:
```yaml
# buf.gen.yaml:
version: v1
managed:
  enabled: true
plugins:
  - plugin: buf.build/bufbuild/es
    opt: target=ts
    out: gen
  - plugin: buf.build/bufbuild/connect-es
    opt: target=ts,import_extension=.ts
    out: gen
```
