### ISSUE TITLE
Generating with target='ts' causes the `<name>_connect.ts` file to import `<name>_pb.js`, causing "module not found error"

### ISSUE THREAD

**Issue by advanderveer** [bufbuild/connect-es#667]
**Describe the bug**

api/v1/query.proto
```Protobuf
syntax = "proto3";

package api.v1;

// Vacancy request for requesting vacancies
message VacanciesRequest{}
// Vacancy response to hold the requested vacancies
message VacanciesResponse{}

// Query side of the CQRS
service QueryService {
    // Get vacancies
    rpc Vacancies(VacanciesRequest) returns (VacanciesResponse);
}
```

buf.gen.yaml
```yaml
version: v1
managed:
  enabled: true
  go_package_prefix:
    default: github.com/crewlinker/next/proto
plugins:
  - name: go
    out: proto
    opt: paths=source_relative
    path: ["go", "run", "google.golang.org/protobuf/cmd/protoc-gen-go"]
  - plugin: connect-go
    out: proto
    opt: paths=source_relative
  - plugin: es
    opt: target=ts
    out: proto
  - plugin: connect-es
    opt: target=ts
    out: proto
```

buf.yaml
```yaml
version: v1
lint:
  use:
    - DEFAULT
    - COMMENTS
    - UNARY_RPC
    - PACKAGE_NO_IMPORT_CYCLE
breaking:
  use:
    - FILE
```

tsconfig.json
```json
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": false,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "noEmit": true,
    "incremental": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "downlevelIteration": true,
    "plugins": [
      {
        "name": "next"
      }
    ]
  },
  "include": ["next-env.d.ts", ".next/types/**/*.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

proto/api/v1/quert_connect.ts
```typescript
// @generated by protoc-gen-connect-es v0.9.1 with parameter "target=ts"
// @generated from file api/v1/query.proto (package api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { VacanciesRequest, VacanciesResponse } from "./query_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Query side of the CQRS
 *
 * @generated from service api.v1.QueryService
 */
export const QueryService = {
  typeName: "api.v1.QueryService",
  methods: {
    /**
     * Get vacancies
     *
     * @generated from rpc api.v1.QueryService.Vacancies
     */
    vacancies: {
      name: "Vacancies",
      I: VacanciesRequest,
      O: VacanciesResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
```

This will cause the following error in next.js: 
```
./proto/api/v1/query_connect.ts:6:0
Module not found: Can't resolve './query_pb.js'
  4 | // @ts-nocheck
  5 | 
> 6 | import { VacanciesRequest, VacanciesResponse } from "./query_pb.js";
  7 | import { MethodKind } from "@bufbuild/protobuf";
  8 | 
  9 | /**

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./app/dashboard/page.tsx
```

Which is true, because query_pb.js doesn't exist. the generated code needs to import query_pb.ts when the ts target is specified.

**To Reproduce**

package.json
```json
{
  "license": "SEE LICENSE IN LICENSE.md",
  "private": true,
  "dependencies": {
    "@bufbuild/connect-node": "^0.9.1",
    "next": "^13.4.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "scripts": {
    "dev": "rimraf .next && next dev",
    "generate": "buf generate",
    "build": "next build",
    "start": "next start",
    "lint": "next lint && prettier --check . '!.next'"
  },
  "prettier": {},
  "devDependencies": {
    "@bufbuild/buf": "^1.20.0-1",
    "@bufbuild/connect": "^0.9.1",
    "@bufbuild/protobuf": "^1.2.1",
    "@bufbuild/protoc-gen-connect-es": "^0.9.1",
    "@bufbuild/protoc-gen-es": "^1.2.1",
    "@types/node": "20.2.5",
    "@types/react": "^18.2.8",
    "@types/react-dom": "^18.2.4",
    "autoprefixer": "^10.4.14",
    "eslint": "8.42.0",
    "eslint-config-next": "13.4.4",
    "eslint-config-prettier": "^8.8.0",
    "postcss": "^8.4.24",
    "postcss-flexbugs-fixes": "^5.0.2",
    "postcss-preset-env": "^8.4.2",
    "prettier": "^2.8.8",
    "rimraf": "^5.0.1",
    "tailwindcss": "^3.3.2",
    "typescript": "~5.0.2"
  },
  "browserslist": [
    ">0.3%",
    "not dead",
    "not op_mini all"
  ],
  "eslintConfig": {
    "extends": [
      "next/core-web-vitals",
      "prettier"
    ]
  },
  "postcss": {
    "plugins": {
      "tailwindcss/nesting": {},
      "tailwindcss": {},
      "autoprefixer": {},
      "postcss-flexbugs-fixes": {},
      "postcss-preset-env": {
        "autoprefixer": {
          "flexbox": "no-2009"
        },
        "stage": 3,
        "features": {
          "custom-properties": false
        }
      }
    }
  }
}

```
